name: List Files

on: [push]

jobs:
  list-files:
    runs-on: ubuntu-latest 

    steps:
      - uses: actions/checkout@v3
      - name: List files in a directory
        run: |
          cd /home/runner/work/aiid205223-sample-Boomi-CICD/aiid205223-sample-Boomi-CICD/JAN2024CE/QA/UpdateExtensions/
          file_array=()
          for file in $(ls | cut -d '.' -f 1); do
            file_array+=("$file")
          done
          echo "Filenames in an array:"
          echo "${file_array[@]}"
          
          # Comparing with files in the 'deploy' folder
          cd /home/runner/work/aiid205223-sample-Boomi-CICD/aiid205223-sample-Boomi-CICD/JAN2024CE/PROD/deploy/
          for file in $(ls); do
            found=false
            for f in "${file_array[@]}"; do
              if [[ "$f" == "$(basename "$file" .*)" ]]; then
                echo "File $file found in deploy folder."
                found=true
                break
              fi
            done
            if [[ "$found" == false ]]; then
              echo "File $file not found in UpdateExtensions directory."
            fi
          done

          # Continue with the rest of your script...
